### ISSUE TITLE
mov 생성하기 기능 추가 요청

### ISSUE THREAD

**Issue by kohyuk91** [75mm-studio/iomanager#12]
iom -v “csv 생성”

iom -c “copy 및 썸네일 생성”

 **_iom -m “mov 생성”_**  (추가)

iom -x “xlsx 생성”

## Details

1. mov 파일은 plate 폴더에 들어가면 된다.

```
Input
/path/to/input/S001.####exr

Output
/path/to/plate/exr/S001.####.exr
/path/to/plate/S001.mov
```

2. mov 생성 툴 선정

```
가용 프로그램 - Nuke11.3, RV Player, FFMPEG, DJV
CentOS7 에서 생성된 mov가 Windows, Mac, Linux(CentOS)에서 잘 재생되어야 한다.
```

**Comment by khw7096** [comment]
솔루션은 대부분 잘 재생되니 개발자가 편한 솔루션을 선정하면 될듯해요.

**Comment by jyub86** [comment]
Mov 생성에 제가 제안드릴 수 있는 부분은 두가지예요.

    1. Nuke를 사용 - 관련 툴의 개발 경험이 많고 개발 시간이 짧아요. 하지만 비싼 툴인 뉴크가 강요되는 단점이 있어요.
    2. oiio + FFmpeg - 오픈소스들을 사용하는 툴로써 어디서든 사용할 수 있어요. 하지만 속도가 느리고 개발 경험이 없어 개발 시간이 길어지는 단점이 있어요.

제가 혼자 결정하고 진행할 문제는 아닌 것 같아 이슈 사항 공유드립니다.
이 이슈는 썸네일 컬러 건과 연관하여 보시면 될 것 같아요!

**Comment by kohyuk91** [comment]
저는 Nuke 한표...!! Undistort Plate도 뉴크CLI 로 뽑고있는데, 이해하기도 쉽고 편하더라고요 ㅎ

**Comment by khw7096** [comment]
저는 OIIO에 한표. 비용과 앞으로의 OCIO, OIIO 호환성을 위해.

**Comment by kohyuk91** [comment]
오홍. 장기적으로 봤을땐 OIIO 군욥

**Comment by jyub86** [comment]
금주까지 정해주시면 다음 주 부터 개발 시작하겠습니다!
이번 주는 결정 기다리면서 관련 부분들 테스트 진행할께욥

**Comment by khw7096** [comment]
![image](https://user-images.githubusercontent.com/1149996/69107337-5e420f00-0ab4-11ea-86f5-5d8546da300b.png)

**Comment by jyub86** [comment]
추가될 부분에 대해서 말씀드릴께요!

- csv 파일 - 기존 데이터에 추가로 proxy path, colorspace, mov 가 추가됩니다.

    Input Folder Date | Directory Folder | Shot | Thumbnail | Format | FPS | ORG_In | ORG_Out | TW_In. | TW_Out | Repo | Camera | Film Back | Focal Length | Assign | Status | Output | Deadline | Task | Input Path | Plate Path | Proxy Path | Colorspace | Mov

- 명령어는 '-m'이 추가되게 되고, '-c' 로 카피 및 썸네일, mov생성 등이 전부 이루어 집니다.
원본과 동일한 사이즈의 proxy 파일이 '.jpg' 확장자로 생성되고, 이것을 통해 mov가 생성됩니다.
jpg 생성에는 'oiiotool'이 사용되고, mov 생성에는 'ffmpeg'가 사용됩니다.

- proxy파일의 경로 : '/PROJECT/scenes/SHOT/plate/proxy/SHOT.%04d.jpg'
- mov파일의 경로 : '/PROJECT/scenes/SHOT/plate/SHOT.mov'

- 썸네일 생성은 컬러 컨버팅의 이유로 기존 'ffmpeg'에서 'oiiotool'로 변경되었습니다.
이것으로 dpx나 exr의 썸네일을 기존보다 정확한 컬러로 생성할 수 있습니다.

- colorspace는 최신버전의 ocio를 사용합니다.
확장명에 따라 디폴트로 colorspace를 설정하며, 해당 플레이트의 컬러 정보를 알고 있다면 사용자가 직접 csv를 통해 변경할 수 있습니다.
ACES도 사용 가능합니다.

변경해야 하는 부분이나 추가 의견 있으시면 알려주세요.
코드 리펙토링 하는 동안 의견 주신 것들 추가 또는 변경 하겠습니다.

기존의 FFmpeg 말고도, oiiotool과 ocio가 추가로 사용됩니다.

**Comment by khw7096** [comment]
I agree on this. How do you think about it Mr.Hyuk?

**Comment by kohyuk91** [comment]
또 엄청나게 업그레이드 되었군요!! 추가 의견 떠오르면 바로 피드백 드리겠습니다ㅎ 당장은 없네요 :) 고!

**Comment by jyub86** [comment]
혁님! 추가로 사용 되어야 하는 툴이 oiiotool과 ocio툴인데 75mm에서 이 툴들 셋팅 좀 부탁드려도 될까요?
oiiotool은 yum으로, ocio는 git clone으로 설치하실 수 있습니다.

    oiiotool - 
    # yum install OpenImageIO
    # yum install OpenImageIO-iv
    # yum install OpenImageIO-devel
    # yum install OpenImageIO-utils
    # yum install python-OpenImageIO

    ocio - 
    # git clone https://github.com/imageworks/OpenColorIO-Configs

설치하시고 설치된 경로 알려주시면 iomanager에 경로 잡아놓을 수 있을 것 같아요.

**Comment by kohyuk91** [comment]
OCIO 경로
```
/storage/INHOUSE/apps/OpenColorIO-Configs
```

**Comment by jyub86** [comment]
일단 oiiotool의 경로도 "/storage/INHOUSE/apps/openimageio/2.0.11/bin/oiiotool" 라고 가정하고 셋팅해 놓을께요! 나중에 위치나 버전이 혹시 다르다면 말씀해주세요!

**Comment by jyub86** [comment]
업데이트 되었습니다! 사용된 툴의 위치 확인 및 간단한 테스트 부탁드립니다.

**Comment by kohyuk91** [comment]
넵 테스트 해보고 피드백 드리겠습니다 :)

**Comment by kohyuk91** [comment]
```
일단 oiiotool의 경로도 "/storage/INHOUSE/apps/openimageio/2.0.11/bin/oiiotool" 라고 가정하고 셋팅해 놓을께요! 나중에 위치나 버전이 혹시 다르다면 말씀해주세요!
```
openimageio 이거는 따로 컴파일 해줘야하는 건가요?

**Comment by jyub86** [comment]
oiiotool은 oiio설치하시면 같이 포함되어 있습니다.

위에 yum으로 설치 하실 수 있어요!

**Comment by kohyuk91** [comment]
oiiotool 경로
```
/usr/bin/oiiotool
```
yum으로 설치했습니다 :)

**Comment by jyub86** [comment]
네 해당 경로 맞춰서 변경해서 올렸습니다!

**Comment by jyub86** [comment]
업데이트 완료
