### ISSUE TITLE
input이 exr 일때 썸네일이 어둡게 생성되는 이슈

### ISSUE THREAD

**Issue by kohyuk91** [75mm-studio/iomanager#13]
input이 exr 일때 썸네일이 어둡게 생성됩니다.

**Comment by khw7096** [comment]
해당 프로젝트 컬러스페이스가 어떻게되나요?

**Comment by kohyuk91** [comment]
RV에서 확인했습니다.
```

ColorSpace/Transfer Linear
ColorSpace/Primaries Rec709
```

**Comment by khw7096** [comment]
oiio 를 사용하거나 뉴크를 사용할 때가 왔네요. iomanager개발자와 이야기해서 방향을 잡아봐야겠네요.

**Comment by jyub86** [comment]
최초에 말씀드렸던 부분이에요. ffmpeg로만 단순 썸네일 생성 시, 컬러스페이스를 무시하고 진행되었기 때문에 썸네일이 뿌옇거나 어둡게 나오게 되는 것 같아요. 이제 컬러 이야기를 할때가 되었나보네요 ㅎㅎ

**Comment by jyub86** [comment]
아래 이슈에서 같이 이야기 하겠습니다!
https://github.com/75mm-studio/iomanager/issues/12
