### ISSUE TITLE
썸네일 관련 이슈들

### ISSUE THREAD

**Issue by kohyuk91** [75mm-studio/iomanager#2]
1. 구글드라이브 GSuite 권한 이슈.
1. 깃헙 프라이빗 리포에 썸네일들 올려서 주소 땡겨오는 방법.

**Comment by sehwanjo10** [comment]
- 드라이브에 이미지를 선행적으로 올려 놓고, 스크립팅으로 시트화.
[사용되어진 코드](gs/listFilesInFolder.gs)

**Comment by sehwanjo10** [comment]
총용량 : 6.33mb, 10%썸네일 이미지 구글 드라이브 업로드 13분정도 소요.

**Comment by sehwanjo10** [comment]
구글 드라이브 폴더안에 있는 1000샷의 이미지를 .gs 를 통해 시트화 작업 2분7초 소요.

**Comment by kohyuk91** [comment]
GSuite에서도 .gs 스크립트가 잘 실행됩니다!

**Comment by khw7096** [comment]
.gs를 도입하면서 기존에 회의한거랑 달라지는게 있나요?

**Comment by kohyuk91** [comment]
내용은 달라진게 없습니다 ㅎ
한가지 테스트 해보고싶은거는 csv 파일에 생성되는 파일들의 순서랑,
구글드라이브 스프레드 시트에 생성되는 썸네일들의 순서가 일치하는지 봐야할것 같네용!

**Comment by khw7096** [comment]
넹~!

**Comment by khw7096** [comment]
토요일 회의에서 썸네일 생성과정을 지켜봄.
