### ISSUE TITLE
xlsx 파일 생성 기능 추가요청

### ISSUE THREAD

**Issue by kohyuk91** [75mm-studio/iomanager#8]
이 라이브러리를 사용해서  xlsx 파일에 다이렉트로 이미지를 삽입하려고 합니다 ㅎ
그렇게 되면 구글드라이브에 썸네일들을 일일이 올리는 일을 피할수 있고
좀더 깔끔한 워크플로우가 될것 같네요!

https://github.com/jmcnamara/XlsxWriter

**Comment by jyub86** [comment]
현재는 csv파일을 사용하도록 되어있어요. 이미지 파일은 csv파일에는 저장하지 못하는 것으로 알고 있어서, 그렇게되면 아마도 ods나 xlsx로 변경해야 할 것 같아요. 포멧을 변경하려면 사용되고 있는 csv관련 함수들을 전부 수정해야 해서 이 작업은 조금 시간이 걸릴 것 같아요. 그리고 이미지 삽입은 썸네일 컨버팅 이후에야 가능하니까, 썸네일 컨버팅 순서도 변경되어야 할 것 같아요.

**Comment by kohyuk91** [comment]
- 처음에는 csv가 뽑히고
- 이미지 프로세싱이 되고,
- 마지막에 .xlsx 파일이 생성(추가 프로세스)

이 형태를 원해요.

**Comment by kohyuk91** [comment]
.xlsx 파일 생성은 `-x` 명령어를 통해서 진행할 수 있을까요?

```bash
$ iom -v // 1. csv생성
$ iom -c // 2. 복사, 썸네일 생성
$ iom -x // 3. .xlsx생성
```

**Comment by jyub86** [comment]
아 넵 좋아요

**Comment by jyub86** [comment]
추가 완료
